---
# Partition module configuration

initialPartitioningChoice: none
initialSwapChoice: file

userSwapChoices:
  - file

swapFileSize: 2048M

ensureSeparateBoot: false
ensureSeparateHome: false
ensureSeparateRoot: false

# Allow auto-partitioning if desired
allowSchemeEditing: true

enableLuksAutomatedPartitioning: true
luksGeneration: luks2
rootFileSystemType: ext4

# Boot loader configuration
grubInstall: auto
grubSecureboot: false
grubDistributor: "SAOS"
