---
# Welcome module

showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false

requirements:
  minimumStorage: 5000    # 5GB in MiB
  minimumRam: 2048        # 2GB in MiB
  check-internet-connection: false
  internet-is-optional: true
