# NetworkManager configuration for SAOS

[main]
# Don't automatically connect to any network
no-auto-default=*

# IPv6 privacy
ipv6.dhcp-duid=stable-uuid
ipv6.ra-timeout=0

# DNS
dns=systemd

[device]
# Don't manage any devices by default
unmanaged-devices=*,except:type:wifi,except:type:wwan,except:type:ethernet

# WiFi power saving
wifi.powersave=3
