---
modules-search: [ local, /usr/lib/calamares/modules ]

instances:
  - id: partition
    module: partition
    config: partition.conf

  - id: luksopenswaphookcfg
    module: luksopenswaphookcfg
    config: luksopenswaphookcfg.conf

  - id: users
    module: users
    config: users.conf

  - id: grub
    module: grub
    config: grub.conf

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - hwclock
    - services-systemd
    - grub
    - bootloader
    - users
    - displaymanager
    - networkcfg
    - postcfg
  - show:
    - finished

branding: saos

prompt-install: true
dont-report-on-crushing-old-partitions: false
disable-cancel: false
disable-cancel-on-nonetwork: false
